# Dependabot will run on day 21 of each month at 02:21 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '14 3 8 * *'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    assignees:
      - 'User'
    versioning-strategy: 'increase'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '42 2 22 * *'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    assignees:
      - 'User'
